### ISSUE TITLE
Intellij crashes when creating dub project

### ISSUE THREAD

**Issue by pirocks** [kingsleyh/DLanguage#100]
Crash occurred on debian. Using the defualt jre which comes with intelliJ 16. Here is the console output.

`java.lang.IllegalArgumentException: Must specify non-empty 'commandLine' parameter
	at com.intellij.execution.process.BaseOSProcessHandler.<init>(BaseOSProcessHandler.java:65)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:68)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:61)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:54)
	at net.masterthought.dlanguage.module.DLanguageDubModuleBuilder.createDub(DLanguageDubModuleBuilder.java:131)
	at net.masterthought.dlanguage.module.DLanguageDubModuleBuilder.getSourcePaths(DLanguageDubModuleBuilder.java:81)
	at com.intellij.ide.util.projectWizard.JavaModuleBuilder.setupRootModel(JavaModuleBuilder.java:108)
	at net.masterthought.dlanguage.module.DLanguageModuleBuilder.setJavaRootModel(DLanguageModuleBuilder.java:91)
	at net.masterthought.dlanguage.module.DLanguageDubModuleBuilder.setupRootModel(DLanguageDubModuleBuilder.java:51)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.setupModule(ModuleBuilder.java:264)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.createModule(ModuleBuilder.java:257)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.createAndCommitIfNeeded(ModuleBuilder.java:295)
	at com.intellij.ide.util.projectWizard.ModuleBuilder$3.compute(ModuleBuilder.java:344)
	at com.intellij.ide.util.projectWizard.ModuleBuilder$3.compute(ModuleBuilder.java:341)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:922)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.commitModule(ModuleBuilder.java:341)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.commit(ModuleBuilder.java:327)
	at com.intellij.ide.util.projectWizard.JavaModuleBuilder.commit(JavaModuleBuilder.java:174)
	at com.intellij.ide.impl.NewProjectUtil.doCreate(NewProjectUtil.java:149)
	at com.intellij.ide.impl.NewProjectUtil.createFromWizard(NewProjectUtil.java:76)
	at com.intellij.ide.impl.NewProjectUtil.createNewProject(NewProjectUtil.java:71)
	at com.intellij.ide.actions.NewProjectAction.actionPerformed(NewProjectAction.java:31)
	at com.intellij.ui.components.labels.ActionLink$1.linkSelected(ActionLink.java:66)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:145)
	at com.intellij.ui.components.labels.ActionLink.doClick(ActionLink.java:79)
	at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:328)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:793)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:625)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by pirocks** [comment]
fixed after reinstalling dub
