### ISSUE TITLE
Have basic code completion when dcd is not installed/available

### ISSUE THREAD

**Issue by pirocks** [kingsleyh/DLanguage#111]
Title almost says it all. DCD is often slow/unreliable as well as being semi-complicated to set up. Ideally the plugin would come with some kind of basic code completion functionality that would be used when DCD is unavailable.

**Comment by RUSshy** [comment]
This should be priority n° 1 since, that is the most basic function of an IDE

I can live without refactoring tools, but i can't live without proper syntax highlighting / auto-completion and package import suggestion

**Comment by pirocks** [comment]
I have some progress on this front. Just a identifier based search, which ignores scope is fairly trivial to implement. If you want I can create a pull request for a simple identifier based match. There are issues(specifically #129) with more sophisticated completion that I am trying to resolve.

**Comment by pirocks** [comment]
There is very basic support for this on my branch at https://github.com/pirocks/DLanguage/commit/765ceb1cb3cf223a5d166128d81e11516afba589

**Comment by RUSshy** [comment]
I tried to build it, but i had to change the target version, i'm using IntelliJ 2017.1 it was released recently (RC)

And whenever i type i get a NPE:

```make
null
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
	at net.masterthought.dlanguage.utils.PlaceHolderUtils.fillInheritancePlaceHolders(PlaceHolderUtils.java:84)
	at net.masterthought.dlanguage.utils.PlaceHolderUtils.fillPlaceHolders(PlaceHolderUtils.java:25)
	at net.masterthought.dlanguage.utils.DResolveUtil.getDeclarationsVisibleFromElement(DResolveUtil.java:337)
	at net.masterthought.dlanguage.utils.DResolveUtil.findDefinitionNodesStandard(DResolveUtil.java:320)
	at net.masterthought.dlanguage.utils.DResolveUtil.findDefinitionNodes(DResolveUtil.java:192)
	at net.masterthought.dlanguage.utils.DResolveUtil.findDefinitionNodes(DResolveUtil.java:54)
	at net.masterthought.dlanguage.psi.references.DReference.multiResolve(DReference.java:51)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference.resolves(PsiMultiReference.java:59)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference.lambda$static$0(PsiMultiReference.java:44)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1438)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference.chooseReference(PsiMultiReference.java:78)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference.resolve(PsiMultiReference.java:126)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:391)
	at com.intellij.codeInsight.TargetElementUtil.b(TargetElementUtil.java:368)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:238)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:210)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:92)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by pirocks** [comment]
Unless I'm mistaken that seems to be a commit after pirocks@765ceb1. It's also possible that your code contains a declaration/something else that breaks it that my code does not cover. Note that the code on my branch is currently very experimental.

**Comment by RUSshy** [comment]
I'll also try to help, this looks like a step in the right direction :)

**Comment by SingingBush** [comment]
@RUSshy see issue #139 re 2017.1. The develop branch has only just got the changes needed for running in that version of Intellij

**Comment by pirocks** [comment]
As of pull request #164  basic code completion is in develop. Close issue?

**Comment by SingingBush** [comment]
@pirocks ok closing. btw, since pulling latest changes when running the sandbox intellij for bit I'm working on it's taking forever to index. I think I'd opened up the mysqlnative project for testing at the time. Is that something you're aware of / can you take a look? it's probably worth cloning a project like vibe-d for testing. Certainly before merging the recent work into master I think we should spend some time using it with a variety of project from the dub repo.

**Comment by pirocks** [comment]
My first guess is that recover rules should have caused a slowdown in parsing. Will investigate.

**Comment by pirocks** [comment]
My first guess is that recover rules should have caused a slowdown in parsing. Will investigate.

**Comment by pirocks** [comment]
Do you have something other than mysqlnative open? It seems fairly fast for me. The standard library on the other hand is very slow at indexing.
