### ISSUE TITLE
Index of D files fails intermittently when starting intellij 

### ISSUE THREAD

**Issue by kingsleyh** [kingsleyh/DLanguage#28]
the Assert fails - it seems a bit random which file fails though - perhaps the DLexer is not thread safe and intellij indexes concurrently?

Error while indexing /Users/kings/development/projects/DLanguage/tests/gold/lexer/string_dq.d
To reindex this file IDEA has to be restarted
AssertFailedException
	at ddt.melnorme.utilbox.core.Assert$AssertHandler.handleAssert(Assert.java:58)
	at ddt.melnorme.utilbox.core.Assert.checkAssertion(Assert.java:85)
	at ddt.melnorme.utilbox.core.Assert$AssertNamespace.assertTrue(Assert.java:147)
	at ddt.dtool.parser.common.AbstractLexer.next(AbstractLexer.java:68)
	at net.masterthought.dlanguage.lexer.DLexer.advance(DLexer.java:75)
	at com.intellij.lang.cacheBuilder.DefaultWordsScanner.processWords(DefaultWordsScanner.java:88)
	at com.intellij.psi.impl.cache.impl.id.IdTableBuilding$WordsScannerFileTypeIdIndexerAdapter.map(IdTableBuilding.java:139)
	at com.intellij.psi.impl.cache.impl.id.IdTableBuilding$WordsScannerFileTypeIdIndexerAdapter.map(IdTableBuilding.java:126)
	at com.intellij.psi.impl.cache.impl.id.IdIndex$4.map(IdIndex.java:85)
	at com.intellij.psi.impl.cache.impl.id.IdIndex$4.map(IdIndex.java:79)
	at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:398)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1749)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1681)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1629)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:101)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:97)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:274)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1143)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:294)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$3.run(ProgressManagerImpl.java:194)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:281)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:278)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:181)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:288)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:405)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)

**Comment by VISTALL** [comment]
Dont cache getWordsScanner() here 

https://github.com/kingsleyh/DLanguage/blob/master/src/net/masterthought/dlanguage/codeinsight/DFindUsagesProvider.java#L35
