### ISSUE TITLE
Creating a run configuration on Ultimate fails with IAE

### ISSUE THREAD

**Issue by cmeury** [kingsleyh/DLanguage#40]
### Steps to reproduce

1. Cloned DLanguage plugin
2. Opened project with IntelliJ IDEA Ultimate 14.1.5 (SDK IntelliJ IDEA IU-141.2735.5, compared to IDEA IC-139.659.2 which was configured in the repo)
3. Created a run configuration and ran the plugin
4. Created a some dummy D project
5. Created a run configuration, first time it works
6. Create another run configuration

### Observation

* From now on, when I try to add a run configuration - when I click nothing happens and the error below is shown in the event log

````
IllegalArgumentException: Argument for @NotNull parameter 'textWithBrowse' of net/masterthought/dlanguage/run/DLanguageApplicationRunConfigurationEditorForm.initDartFileTextWithBrowse must not be null
````

### Full Stack Trace

````
Argument for @NotNull parameter 'textWithBrowse' of net/masterthought/dlanguage/run/DLanguageApplicationRunConfigurationEditorForm.initDartFileTextWithBrowse must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'textWithBrowse' of net/masterthought/dlanguage/run/DLanguageApplicationRunConfigurationEditorForm.initDartFileTextWithBrowse must not be null
	at net.masterthought.dlanguage.run.DLanguageApplicationRunConfigurationEditorForm.initDartFileTextWithBrowse(DLanguageApplicationRunConfigurationEditorForm.java)
	at net.masterthought.dlanguage.run.DLanguageApplicationRunConfigurationEditorForm.<init>(DLanguageApplicationRunConfigurationEditorForm.java:40)
	at net.masterthought.dlanguage.run.DLanguageApplicationRunConfiguration.getConfigurationEditor(DLanguageApplicationRunConfiguration.java:38)
	at net.masterthought.dlanguage.run.DLanguageApplicationRunConfiguration.getConfigurationEditor(DLanguageApplicationRunConfiguration.java:18)
	at com.intellij.execution.impl.ConfigurationSettingsEditor.<init>(ConfigurationSettingsEditor.java:220)
	at com.intellij.execution.impl.ConfigurationSettingsEditorWrapper.<init>(ConfigurationSettingsEditorWrapper.java:67)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.<init>(SingleConfigurationConfigurable.java:65)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.editSettings(SingleConfigurationConfigurable.java:99)
	at com.intellij.execution.impl.RunConfigurable.a(RunConfigurable.java:374)
	at com.intellij.execution.impl.RunConfigurable.access$600(RunConfigurable.java:76)
	at com.intellij.execution.impl.RunConfigurable$4.valueChanged(RunConfigurable.java:263)
	at javax.swing.JTree.fireValueChanged(JTree.java:2926)
	at javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3387)
	at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:635)
	at com.intellij.ui.treeStructure.Tree$MySelectionModel.fireValueChanged(Tree.java:654)
	at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1093)
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:294)
	at javax.swing.JTree.setSelectionPaths(JTree.java:1646)
	at javax.swing.JTree.setSelectionRows(JTree.java:1728)
	at javax.swing.JTree.setSelectionRow(JTree.java:1703)
	at com.intellij.util.ui.tree.TreeUtil$1.run(TreeUtil.java:523)
	at com.intellij.util.ui.tree.TreeUtil.showAndSelect(TreeUtil.java:574)
	at com.intellij.util.ui.tree.TreeUtil.showRowCentered(TreeUtil.java:466)
	at com.intellij.util.ui.tree.TreeUtil.showRowCentered(TreeUtil.java:457)
	at com.intellij.util.ui.tree.TreeUtil.showRowCentred(TreeUtil.java:452)
	at com.intellij.util.ui.tree.TreeUtil.selectPath(TreeUtil.java:383)
	at com.intellij.util.ui.tree.TreeUtil.selectInTree(TreeUtil.java:833)
	at com.intellij.util.ui.tree.TreeUtil.selectInTree(TreeUtil.java:821)
	at com.intellij.execution.impl.RunConfigurable$6.run(RunConfigurable.java:320)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:778)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:465)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1614)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1571)
	at com.intellij.execution.actions.EditRunConfigurationsAction.actionPerformed(EditRunConfigurationsAction.java:47)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:746)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
````

**Comment by cmeury** [comment]
I'm completely new to IntelliJ IDEA plugin development, so it might be a simple oversight. Still I felt the setup was pretty straight forward.

**Comment by kingsleyh** [comment]
When I first built the plugin the instructions I followed stated I should use the community edition SDK which is what I did and have not had any issues with it - plus it allows to debug into the source code. The getting started documents do say that you should be able to use either the community edition SDK or the Ultimate one however I have never tried with the ultimate one before. See docs here: http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/setting_up_environment.html#configuring-intellij-platform-sdk

I have not encountered this exception before - but it would be worth checking it using the community edition to see if the problem still persists. Also I have noted that differences in the intellij releases often cause a lot of backward compatibility issues regarding the plugins. 

I am in the middle of a complete re-write of the plugin so there will be massive upheaval and re-writing over the next few months. The current incarnation of the plugin was mostly a learning experience so there are many bugs and issues which I now know how to fix.

I will however investigate using the ultimate SDK as well and fix any issues I encounter as they come.

**Comment by cmeury** [comment]
That was a quick response, thanks! I'll try out the Community Edition and report back. Good to hear you're rewriting. Are you tracking that effort on GitHub somewhere?

**Comment by cmeury** [comment]
This does not happen with the Community Edition. It's the same version though: `IntelliJ IDEA Community Edition IC-141.2735.5`

**Comment by kingsleyh** [comment]
Great thanks for letting me know. I will be revising the work soon and raising issues as required to track the work
